### PR TITLE
Partial support for the Dell U2715H

### PR DESCRIPTION
**Pull request by 153957**
Setting the contrast does not work.
Whenever the slide is modified it sets the display contrast to 25.

### CODE REVIEW

**Comment by Kalvin126** [comment]
Hm Interesting, This is also the case on my Dells. It was working before. I will need to look into this.

**Comment by Kalvin126** [comment]
Commit a92d2877d2eddac65105d6dd29a17587df0958a8 fixes #1 

The issue was that the contrast value was being calculated with NSInteger types when it should have been double. Please test again and let me know if the issue was fixed.

**Comment by 153957** [comment]
Ok I will check with the U2715H tonight.
I just checked that Brightness and Contrast now work properly for U2415H.

**Comment by 153957** [comment]
It works fine now, Ill make a new PR, see #2

**Pull request closed without merging**
