### PR TITLE
Add Acer G276HL

### PR DESCRIPTION
**Pull request by rightpad**
Tested my monitor and I can confirm that lowering and raising the brightness and contrast settings work, however default values are not correct. My monitor only goes up to a value of 100 for both the backlight and contrast, but the app upper limit for both is 141 (it seems as though the monitor ignores anything past 100). Also, the current value of the settings on the monitor are not correctly read upon app startup or monitor connection (always defaulting to 127 out of 141). Regardless of these bugs, the core functionality of the app is working. I would open an issue for this but I can't seem to do that here (perhaps because this is a fork?). 

I included some (truncated) debug output as well. VCP goes from 0 to ff.

`2/23/16 10:50:53.301 PM Brightness Menulet[80170]: PreferencesController: Pref Window alloc
2/23/16 10:50:56.289 PM Brightness Menulet[80170]: readDisplay:478179687 withValue: failed need to retry...
2/23/16 10:50:56.289 PM Brightness Menulet[80170]: VCP: 0 - 127 / 141 
2/23/16 10:50:56.290 PM Brightness Menulet[80170]: readDisplay:478179687 withValue: failed need to retry...
2/23/16 10:50:56.290 PM Brightness Menulet[80170]: VCP: 1 - 127 / 141 
2/23/16 10:50:56.291 PM Brightness Menulet[80170]: readDisplay:478179687 withValue: failed need to retry...
2/23/16 10:50:56.291 PM Brightness Menulet[80170]: VCP: 2 - 127 / 141 
2/23/16 10:50:56.292 PM Brightness Menulet[80170]: readDisplay:478179687 withValue: failed need to retry...
`
...
`
2/23/16 10:50:56.417 PM Brightness Menulet[80170]: VCP: fd - 127 / 141 
2/23/16 10:50:56.417 PM Brightness Menulet[80170]: readDisplay:478179687 withValue: failed need to retry...
2/23/16 10:50:56.418 PM Brightness Menulet[80170]: VCP: fe - 127 / 141 
2/23/16 10:50:56.418 PM Brightness Menulet[80170]: readDisplay:478179687 withValue: failed need to retry...
2/23/16 10:50:56.418 PM Brightness Menulet[80170]: VCP: ff - 127 / 141 
2/23/16 10:50:58.718 PM Brightness Menulet[80170]: PreferencesController: preferenceWindow Dealloc
`

### CODE REVIEW

**Comment by Kalvin126** [comment]
Can you post the VCP reading for 0x10 and 0x12?

**Comment by Kalvin126** [comment]
Issues was turned off for some reason. I have now opened it back up.

**Comment by rightpad** [comment]
> Can you post the VCP reading for 0x10 and 0x12?

### 0x10:

`
2/23/16 10:50:56.300 PM Brightness Menulet[80170]: readDisplay:478179687 withValue: failed need to retry...
2/23/16 10:50:56.300 PM Brightness Menulet[80170]: VCP: 10 - 127 / 141 
`

### 0x12:

`
2/23/16 10:50:56.301 PM Brightness Menulet[80170]: readDisplay:478179687 withValue: failed need to retry...
2/23/16 10:50:56.301 PM Brightness Menulet[80170]: VCP: 12 - 127 / 141 
`

**Comment by Kalvin126** [comment]
and what if you lower the brightness under 100?

**Comment by rightpad** [comment]
The slider only goes to 0, but if I manually key in `-2` on the preferences pane, the backlight on my monitor is set to 100. 

I created a gist with the full console dump below

https://gist.github.com/peterdimou/f55a064c50c2f80a685f

**Comment by Kalvin126** [comment]
While it does change your brightness, I can't say this tool works for your monitor properly. Your Acer must not support MCCS properly. It reports the brightness VCP max value as 141, yet you can't set it to something say 50?

**Comment by rightpad** [comment]
I can set both the backlight and contrast to 50 or any other arbitrary number between 0 and 100 (range my monitor supports) just fine. The issue seems to be with finding the max range and reading the current value on app launch / return from monitor sleep. Core functionality is there, just an annoying issue prevents it from being 100%. 

I understand if you don't want to merge this PR because of that. May I propose another column in the table on the Readme called "partially working" with a note section at the bottom? I know it would be useful for people like me that don't have Dell brand monitors and are looking to set the backlight through DDC. I know at the very least I'll still be using this app & fork to set my monitor backlight.

**Comment by rightpad** [comment]
I'm not sure if this helps (since I don't know much about DDC), but in the user manual for the monitor it's stated that the monitor supports the DDC2B standard.

**Comment by rightpad** [comment]
Sorry for three consecutive comments in a row, but I think I found something that might really help. I did some research and found some software for Windows called softMCCS that enumerates all capabilities for a monitor regarding DDC/CI and MCCS. I successfully ran it and uploaded the report to a gist here:

https://gist.github.com/peterdimou/a18928e5e3282425f19f

Hopefully that will give you the information you need to either supply a fix, or determine that the monitor is only partially supported. Also, thank you for being active on this PR/issue, I appreciate it.

**Comment by rightpad** [comment]
Closing this pull request so it doesn't stagnate on the repo. If the maintainer feels like fixing the bugs with this monitor then I would be more than happy to both open an issue and provide more data if necessary.

**Pull request closed without merging**
